"""add_user

Revision ID: 57bc201a2130
Revises: 63dc2fca65e1
Create Date: 2025-06-09 17:08:25.720123

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57bc201a2130"
down_revision: Union[str, None] = "63dc2fca65e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("social_id", sa.BigInteger(), nullable=False),
    sa.Column("username", sa.String(length=50), nullable=True),
    sa.Column("registration_date", sa.DateTime(), nullable=True),
    sa.Column("taps", sa.BigInteger(), nullable=False),
    sa.Column("name", sa.Text(), nullable=True),
    sa.Column("info", sa.Text(), nullable=True),
    sa.Column("photo", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
